122 Publish All Projects
codecovevienna/gittt-cli pull request #100
Opened 2021-01-06 17:59 UTC by lombad

It should be possible to publish all projects an all the links with one single command e.g. gittt publish -all

AC:
- [x] All data gets published with a single command

2021-01-06 19:04 UTC, matthiaseigner requested changes
2 small questions

2021-01-06 19:04 UTC, matthiaseigner commented on app.ts
> +    if (projectIntegrationLinks.length === 1 && projectIntegrationLinks[0].integrationLinks.length === 0) {
what If the second project in the array does not have any links? I will not crash but no error would be displayed - correct?

2021-01-06 19:04 UTC, matthiaseigner commented on test/unit/app.test.ts
> +        // const getProjectByNameStub = sinon.stub().returns({
could this be removed?

2021-01-07 19:36 UTC, lombad commented on app.ts
> +    if (projectIntegrationLinks.length === 1 && projectIntegrationLinks[0].integrationLinks.length === 0) {
Cool finding, I added a warning in 804d38e4c40e13b6a911b448b9828d7dfcd49b01

2021-01-07 19:36 UTC, lombad commented on test/unit/app.test.ts
> +        // const getProjectByNameStub = sinon.stub().returns({
removed in 2d2539f6cf36ecb1b0466673806f0ed0235b3f25

2021-01-07 22:15 UTC, matthiaseigner approved these changes

2021-01-07 22:15 UTC, merged