55 resources api o auth
codecovevienna/gittt-cli pull request #98
Opened 2020-12-18 23:41 UTC by eiabea

2020-12-30 18:09 UTC, lombad requested changes

2020-12-30 18:09 UTC, lombad commented on test/unit/app.test.ts
> +          assert.isTrue(addOrUpdateLinkStub.notCalled);
If a different error would cause that `addOrUpdateLinkStub` is not called, this test would not fail. Is there a method to check for the actual failure.

2020-12-30 18:09 UTC, lombad commented on test/unit/validation.helper.test.ts
> +    assert.isString(ValidationHelper.validateUsername(undefined));
Is the assert correct ? Should it not be `assert.isFalse(...)` ?

2021-01-02 22:01 UTC, eiabea commented on test/unit/validation.helper.test.ts
> +    assert.isString(ValidationHelper.validateUsername(undefined));
No, the validate function for `inquirer` expects to get a boolean `true` if the validation is correct or a string which means the validation failed and the returned string is displayed as error message :unamused:

2021-01-02 22:01 UTC, eiabea commented on test/unit/validation.helper.test.ts
> +    assert.isString(ValidationHelper.validatePassword(undefined));
No, the validate function for `inquirer` expects to get a boolean `true` if the validation is correct or a string which means the validation failed and the returned string is displayed as error message :unamused:

2021-01-02 22:17 UTC, eiabea commented on app.ts
> +const MULTIPIE_OAUTH_CLIENT_SECRET = "3d7d8937-bb46-4ac6-9b1e-0912e1ca1195";
As discussed, i removed the client secret and asking the user for it when creating a new link to avoid having it in the code base. The client secret which already got into the version control got revoked :wink:

2021-01-02 22:17 UTC, eiabea commented on app.ts
> +    // TODO maybe outsource this to own oauth helper
Moved everything oauth related to an own `AuthHelper`

2021-01-02 22:18 UTC, eiabea commented on helper/project.ts
> +  //           const migratedMultipieLink: IMultipieInputLink = link as IMultipieInputLink;
Removed in newest changes

2021-01-02 22:18 UTC, eiabea commented on helper/validation.ts
> +  public static validateUsername = (input: any): boolean | string | Promise<boolean | string> => {
Added regex to check for username

2021-01-02 22:18 UTC, eiabea commented on helper/validation.ts
> +  public static validatePassword = (input: any): boolean | string | Promise<boolean | string> => {
Added regex to check for valid password

2021-01-02 22:19 UTC, eiabea commented on test/unit/app.test.ts
> +          assert.isTrue(addOrUpdateLinkStub.notCalled);
Couldn't think of an easy solution right now :disappointed:

2021-01-04 10:09 UTC, lombad commented on app.ts
> +const MULTIPIE_OAUTH_CLIENT_SECRET = "3d7d8937-bb46-4ac6-9b1e-0912e1ca1195";
Super clean solution. Thx

2021-01-04 10:15 UTC, lombad commented on test/unit/validation.helper.test.ts
> +    assert.isString(ValidationHelper.validateUsername(undefined));
Thx for the clarification

2021-01-04 10:17 UTC, lombad approved these changes

2021-01-04 10:18 UTC, lombad commented on test/unit/app.test.ts
> +          assert.isTrue(addOrUpdateLinkStub.notCalled);
Ok we will keep it for now.

2021-01-05 10:04 UTC, merged